[features]
seeds = false
[programs.localnet]
cpipda = "6UBeznVw8PWyhVPa9Sk99nMTR8C5GUt2k535ov4Pqvfg"
proxy = "HKbTE9zSwQFx1vaXGxSe7EyFqdrmVyiEyeeuLWVwPo7W"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/knox/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
